### ISSUE TITLE
"Top" list not being displayed in Detritus

### ISSUE THREAD

**Issue by joshkunz** [cosmocode/dokuwiki-plugin-top#7]
Using the `sqlite` plugin's management interface I queried the `toppages` table and the plugin is correctly updating the `value` field. However when I try to include `{{top}}` in any page it doesn't produce anything at all. I'm running "Detritus" fully patched.

**Comment by micgro42** [comment]
I can confirm this bug. For me, only the wiki startpage is displayed.

**Comment by splitbrain** [comment]
@micgro42 can you look into it please?

**Comment by micgro42** [comment]
@Joshkunz I assume your wiki is non-public?

**Comment by joshkunz** [comment]
@micgro42 Yes it is. I'll try that patch.

**Comment by joshkunz** [comment]
@micgro42 Looks like that was the issue. The list is displaying as expected now, thanks for your patch.
